// routes/printify.js — Printify integration
import express from "express";
import { supabase, logAgent, enqueueTask } from "../lib/supabase.js";
export const printifyRouter = express.Router();
const PRINTIFY_KEY=process.env.PRINTIFY_API_KEY||"",PRINTIFY_SHOP=process.env.PRINTIFY_SHOP_ID||"";
function ph(){return{"Authorization":`Bearer ${PRINTIFY_KEY}`,"Content-Type":"application/json"};}
printifyRouter.get("/shops",async(req,res)=>{try{const r=await fetch("https://api.printify.com/v1/shops.json",{headers:ph()});if(!r.ok)return res.status(r.status).json({error:`Printify ${r.status}`});const d=await r.json();if(d?.[0]?.id&&!PRINTIFY_SHOP)console.log("Set PRINTIFY_SHOP_ID =",d[0].id);res.json(d);}catch(e){res.status(500).json({error:e.message});}});
printifyRouter.get("/products",async(req,res)=>{try{const r=await fetch(`https://api.printify.com/v1/shops/${PRINTIFY_SHOP}/products.json?limit=20`,{headers:ph()});if(!r.ok){const e=await r.text();return res.status(r.status).json({error:`Printify ${r.status}`,detail:e.slice(0,200)});}const d=await r.json();if(d.data?.length)for(const p of d.data)await supabase.from("products").upsert({external_id:p.id,platform:"printify",title:p.title,status:p.visible?"active":"draft",updated_at:new Date().toISOString()},{onConflict:"external_id,platform"}).catch(()=>{});res.json(d);}catch(e){res.status(500).json({error:e.message});}});
printifyRouter.post("/products",async(req,res)=>{const{product,publish_immediately}=req.body;if(!publish_immediately){const t=await enqueueTask({agent:"KOFI",task_type:"inventory_check",payload:{action:"create_printify_product",product,requires_approval:true},priority:2});return res.json({queued:true,task_id:t.id,message:"Requires approval"});}try{const r=await fetch(`https://api.printify.com/v1/shops/${PRINTIFY_SHOP}/products.json`,{method:"POST",headers:ph(),body:JSON.stringify(product)});const d=await r.json();await logAgent("KOFI",`Created Printify: ${d.id}`,"success");res.status(r.status).json(d);}catch(e){res.status(500).json({error:e.message});}});
printifyRouter.post("/products/:id/publish",async(req,res)=>{const t=await enqueueTask({agent:"KWAME",task_type:"sales_optimization",payload:{action:"publish_printify_product",product_id:req.params.id,requires_approval:true},priority:1});res.json({queued:true,task_id:t.id,message:"Publishing requires approval"});});
printifyRouter.get("/orders",async(req,res)=>{try{const r=await fetch(`https://api.printify.com/v1/shops/${PRINTIFY_SHOP}/orders.json?limit=20`,{headers:ph()});if(!r.ok)return res.status(r.status).json({error:`Printify ${r.status}`});res.json(await r.json());}catch(e){res.status(500).json({error:e.message});}});
printifyRouter.get("/inventory",async(req,res)=>{try{const r=await fetch(`https://api.printify.com/v1/shops/${PRINTIFY_SHOP}/products.json?limit=50`,{headers:ph()});if(!r.ok)return res.status(r.status).json({error:`Printify ${r.status}`});const d=await r.json();const inv=(d.data||[]).map(p=>({id:p.id,title:p.title,visible:p.visible,variants:(p.variants||[]).map(v=>({id:v.id,title:v.title,enabled:v.is_enabled,price:v.price/100}))}));for(const i of inv){const{data:dbP}=await supabase.from("products").select("id").eq("external_id",i.id).eq("platform","printify").single();if(dbP?.id)await supabase.from("inventory_snapshots").insert({product_id:dbP.id,platform:"printify",quantity:i.variants.filter(v=>v.enabled).length}).catch(()=>{});}res.json({inventory:inv});}catch(e){res.status(500).json({error:e.message});}});
printifyRouter.post("/mockups",async(req,res)=>{const t=await enqueueTask({agent:"AMARA",task_type:"marketing_campaign",payload:{action:"generate_mockups",product:req.body},priority:4});res.json({queued:true,task_id:t.id});});
printifyRouter.post("/webhooks/order",express.raw({type:"application/json"}),async(req,res)=>{res.sendStatus(200);const e=JSON.parse(req.body);await logAgent("KOFI",`Printify order: ${e.type}`,"info",e);});
