// workers/scheduler.js — SWARM OS Worker v2 (fixes: smart-seed, retry, security)
import cron from "node-cron";
import { enqueueTask, claimNextTask, updateTaskStatus, updateSchedulerState, logAgent, recordHealth, saveAgentOutput, supabase } from "../lib/supabase.js";
import { executeTask } from "../agents/executor.js";

const WORKER_ID = `worker-${process.env.RENDER_INSTANCE_ID || "local"}-${Date.now()}`;
console.log(`SWARM OS Scheduler starting — ${WORKER_ID}`);

async function processAgentQueue(agent) {
  try {
      const task = await claimNextTask(agent);
          if (!task) return;
              console.log(`[${agent}] Claimed: ${task.task_type} (${task.id})`);
                  try {
                        const result = await executeTask(task);
                              if (result?.requires_approval) {
                                      await updateTaskStatus(task.id, "awaiting_approval", result);
                                              await logAgent(agent, `Awaiting approval: ${task.task_type}`, "warn", result, task.id);
                                                    } else {
                                                            await updateTaskStatus(task.id, "completed", result);
                                                                    await enqueueFollowUps(task, result);
                                                                          }
                                                                              } catch (err) {
                                                                                    await updateTaskStatus(task.id, "failed", null, err.message);
                                                                                          await logAgent(agent, `Failed: ${err.message}`, "error", null, task.id);
                                                                                              }
                                                                                                } catch (err) { console.error(`[${agent}] Queue error:`, err.message); }
                                                                                                }

                                                                                                // FIX 4: Auto-retry failed tasks (every 5 min, tasks failed > 2 min ago)
                                                                                                async function retryFailedTasks() {
                                                                                                  try {
                                                                                                      const { data: failed, count } = await supabase
                                                                                                            .from("tasks").select("id", { count: "exact" })
                                                                                                                  .eq("status", "failed")
                                                                                                                        .lt("updated_at", new Date(Date.now() - 120000).toISOString())
                                                                                                                              .lt("priority", 9);
                                                                                                                                  if (!count) return;
                                                                                                                                      const ids = (failed || []).map(t => t.id);
                                                                                                                                          await supabase.from("tasks").update({ status: "pending", error: null, started_at: null, updated_at: new Date().toISOString() }).in("id", ids);
                                                                                                                                              console.log(`[RETRY] Reset ${count} failed tasks to pending`);
                                                                                                                                                } catch (err) { console.error("[RETRY] Error:", err.message); }
                                                                                                                                                }

                                                                                                                                                async function enqueueFollowUps(completedTask, result) {
                                                                                                                                                  const { task_type } = completedTask;
                                                                                                                                                    if (task_type === "trend_research" && result?.top_pick) {
                                                                                                                                                        await enqueueTask({ agent: "AISHA", task_type: "seo_generation", payload: { title: result.top_pick, keywords: result.trends?.map(t => t.keyword) || [], platform: "etsy" }, priority: 3, parentTaskId: completedTask.id });
                                                                                                                                                          await enqueueTask({ agent: "AMARA", task_type: "generate_etsy_title",       payload: { keyword: result.top_pick }, priority: 3, parentTaskId: completedTask.id });
                                                                                                                                                          await enqueueTask({ agent: "AMARA", task_type: "generate_etsy_description", payload: { keyword: result.top_pick }, priority: 3, parentTaskId: completedTask.id });
                                                                                                                                                          await enqueueTask({ agent: "AMARA", task_type: "generate_etsy_tags",        payload: { keyword: result.top_pick }, priority: 3, parentTaskId: completedTask.id });
                                                                                                                                                          await enqueueTask({ agent: "AMARA", task_type: "generate_social_caption",   payload: { keyword: result.top_pick }, priority: 3, parentTaskId: completedTask.id });
                                                                                                                                                          console.log(`[PIPELINE] NANA->AISHA+4xAMARA queued for "${result.top_pick}"`);
                                                                                                                                                          }  if (task_type === "generate_etsy_title" && result?.title) {
                                                                                                                                                          await saveAgentOutput({ taskId: completedTask.id, agent: "AMARA", outputType: "etsy_title", etsyTitle: result.title, confidence: result.confidence || 0.8 });
                                                                                                                                                      }
                                                                                                                                                    if (task_type === "generate_etsy_description" && result?.description) {
                                                                                                                                                          await saveAgentOutput({ taskId: completedTask.id, agent: "AMARA", outputType: "etsy_description", etsyDescription: result.description, confidence: result.confidence || 0.8 });
                                                                                                                                                      }
                                                                                                                                                    if (task_type === "generate_etsy_tags" && result?.tags) {
                                                                                                                                                          await saveAgentOutput({ taskId: completedTask.id, agent: "AMARA", outputType: "etsy_tags", etsyTags: result.tags, confidence: result.confidence || 0.8 });
                                                                                                                                                      }
                                                                                                                                                    if (task_type === "generate_social_caption" && result?.caption) {
                                                                                                                                                          await saveAgentOutput({ taskId: completedTask.id, agent: "AMARA", outputType: "social_caption", socialCaption: result.caption, confidence: result.confidence || 0.8 });
                                                                                                                                                      }
                                                                                                                                                            if (task_type === "seo_generation" && result?.title) {
                                                                                                                                                                await enqueueTask({ agent: "AMARA", task_type: "social_caption", payload: { product: result.title, platform: "instagram", count: 3 }, priority: 4, parentTaskId: completedTask.id });
                                                                                                                                                                  }
                                                                                                                                                                    if (task_type === "analytics_report" && result?.underperformers?.length > 0) {
                                                                                                                                                                        await enqueueTask({ agent: "KWAME", task_type: "sales_optimization", payload: { sales: result }, priority: 4, parentTaskId: completedTask.id });
                                                                                                                                                                          }
                                                                                                                                                                            if (task_type === "inventory_check" && result?.status === "critical") {
                                                                                                                                                                                await enqueueTask({ agent: "ZARA", task_type: "inventory_check", payload: { low_stock: result.low_stock, context: "critical_alert" }, priority: 1, parentTaskId: completedTask.id });
                                                                                                                                                                                  }
                                                                                                                                                                                  }

                                                                                                                                                                                  async function runHourlyTrendScan() {
                                                                                                                                                                                    const categories = ["wall art","digital prints","home decor","affirmation prints","black art"];
                                                                                                                                                                                      for (const category of categories) await enqueueTask({ agent: "NANA", task_type: "trend_research", payload: { category }, priority: 3 });
                                                                                                                                                                                        await updateSchedulerState("hourly_trend_scan", "ok");
                                                                                                                                                                                        }
                                                                                                                                                                                        async function runHourlyInventoryCheck() { await enqueueTask({ agent: "KOFI", task_type: "inventory_check", payload: {}, priority: 2 }); await updateSchedulerState("hourly_inventory_check", "ok"); }
                                                                                                                                                                                        async function runHourlyOrderMonitor() { await enqueueTask({ agent: "SEUN", task_type: "analytics_report", payload: { period: "last_hour" }, priority: 2 }); await updateSchedulerState("hourly_order_monitor", "ok"); }
                                                                                                                                                                                        async function runDailySEO() {
                                                                                                                                                                                          const { data: trends } = await supabase.from("trends").select("*").order("score", { ascending: false }).limit(5);
                                                                                                                                                                                            if (trends?.length) for (const t of trends) await enqueueTask({ agent: "AISHA", task_type: "seo_generation", payload: { title: t.keyword, keywords: [t.keyword], platform: "etsy" }, priority: 4 });
                                                                                                                                                                                              await updateSchedulerState("daily_seo_generation", "ok");
                                                                                                                                                                                              }
                                                                                                                                                                                              async function runDailyAnalytics() {
                                                                                                                                                                                                await enqueueTask({ agent: "SEUN", task_type: "analytics_report", payload: { period: "last_24_hours" }, priority: 3 });
                                                                                                                                                                                                  await enqueueTask({ agent: "ABENA", task_type: "financial_report", payload: { period: "today" }, priority: 4 });
                                                                                                                                                                                                    await updateSchedulerState("daily_analytics_report", "ok");
                                                                                                                                                                                                    }
                                                                                                                                                                                                    async function runWeeklyCampaign() { await enqueueTask({ agent: "AMARA", task_type: "marketing_campaign", payload: { goal: "weekly_review" }, priority: 5 }); await updateSchedulerState("weekly_campaign_review", "ok"); }
                                                                                                                                                                                                    async function runWeeklyAudit() {
                                                                                                                                                                                                      await enqueueTask({ agent: "KWAME", task_type: "sales_optimization", payload: { context: "weekly_audit" }, priority: 5 });
                                                                                                                                                                                                        await enqueueTask({ agent: "DELE", task_type: "pricing_analysis", payload: { context: "weekly_review" }, priority: 5 });
                                                                                                                                                                                                          await updateSchedulerState("weekly_product_audit", "ok");
                                                                                                                                                                                                          }
                                                                                                                                                                                                          async function runHealthCheck() {
                                                                                                                                                                                                            for (const svc of ["anthropic","supabase","shopify","etsy"]) {
                                                                                                                                                                                                                try {
                                                                                                                                                                                                                      const start = Date.now();
                                                                                                                                                                                                                            const r = await fetch(`https://swarm-app-3nch.onrender.com/api/health/${svc}`, { signal: AbortSignal.timeout(8000) });
                                                                                                                                                                                                                                  const d = await r.json();
                                                                                                                                                                                                                                        await recordHealth(svc, d.status === "ok" ? "ok" : "fail", Date.now()-start, d);
                                                                                                                                                                                                                                            } catch (e) { await recordHealth(svc, "fail", null, { error: e.message }); }
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                              const AGENTS = ["NANA","KOFI","AMARA","KWAME","FATIMA","SEUN","AISHA","IBRAHIM","ZARA","DELE","IMANI","ABENA"];
                                                                                                                                                                                                                                              async function runWorkerLoop() { for (const agent of AGENTS) await processAgentQueue(agent); }

                                                                                                                                                                                                                                              cron.schedule("*/30 * * * * *", runWorkerLoop);
                                                                                                                                                                                                                                              cron.schedule("*/5 * * * *", retryFailedTasks); // FIX 4: retry
                                                                                                                                                                                                                                              cron.schedule("0 * * * *", runHourlyTrendScan);
                                                                                                                                                                                                                                              cron.schedule("5 * * * *", runHourlyInventoryCheck);
                                                                                                                                                                                                                                              cron.schedule("10 * * * *", runHourlyOrderMonitor);
                                                                                                                                                                                                                                              cron.schedule("0 6 * * *", runDailySEO);
                                                                                                                                                                                                                                              cron.schedule("15 6 * * *", runDailyAnalytics);
                                                                                                                                                                                                                                              cron.schedule("0 7 * * 1", runWeeklyCampaign);
                                                                                                                                                                                                                                              cron.schedule("30 7 * * 1", runWeeklyAudit);
                                                                                                                                                                                                                                              cron.schedule("*/15 * * * *", runHealthCheck);

                                                                                                                                                                                                                                              // FIX 3: Smart seed — skip if >= 3 pending tasks created in last 30 min
                                                                                                                                                                                                                                              (async () => {
                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                    const since = new Date(Date.now() - 1800000).toISOString();
                                                                                                                                                                                                                                                        const { count } = await supabase.from("tasks").select("*", { count: "exact", head: true }).eq("status", "pending").gt("created_at", since);
                                                                                                                                                                                                                                                            if ((count || 0) < 3) {
                                                                                                                                                                                                                                                                  console.log(`[SEED] ${count} recent pending — seeding`);
                                                                                                                                                                                                                                                                        await runHourlyTrendScan();
                                                                                                                                                                                                                                                                              await runDailyAnalytics();
                                                                                                                                                                                                                                                                                    console.log("SWARM OS: Tasks seeded");
                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                              console.log(`[SEED] ${count} pending tasks exist — skipping duplicate seed`);
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                    } catch(e) { console.error("Seed error:", e.message); }
                                                                                                                                                                                                                                                                                                    })();
                                                                                                                                                                                                                                                                                                    console.log("SWARM OS: All cron jobs registered");
                                                                                                                                                                                                                                                                                                    
